{
 "title": "Flexpool overview",
 "description": "Global hashrates, shares, balance and revenue estimation",
 "tags": [
  "flexpool",
  "mining"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "miner",
    "query": "SHOW TAG VALUES FROM flexpool_miner_stats WITH KEY = \"miner\""
   },
   {
    "name": "currency",
    "query": "SHOW TAG VALUES FROM currencies WITH KEY = \"to\""
   },
   {
    "name": "exchange_rate",
    "query": "select value from currencies where \"to\" =~ /^$currency$/ order by desc limit 1"
   },
   {
    "name": "timezone",
    "query": "Africa/Tunis,America/Chicago,America/Fortaleza,America/Los_Angeles,America/Moncton,America/New_York,America/Sao_Paulo,America/St_Johns,America/Toronto,America/Vancouver,Asia/Jakarta,Asia/Karachi,Asia/Kolkata,Asia/Singapore,Europe/Berlin,Europe/Kiev,Europe/London,Europe/Moscow,Europe/Paris,Europe/Zagreb,Europe/Zurich"
   }
  ]
 },
 "panels": [
  { "title": "Balance and revenue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily revenue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ETH", "label": "income" }
   ],
   "targets": [
    {
     "alias": "income",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "flexpool_miner_balance",
     "query": "SELECT sum(balance_increase)/1000000000000000000 FROM (select non_negative_difference(\"result\") AS balance_increase FROM \"flexpool_miner_balance\" WHERE \"miner\" =~ /^$miner$/ AND $timeFilter) GROUP BY time(1d) TZ('$timezone');",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1d" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "income (fiat)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(balance_increase)/1000000000000000000*$exchange_rate FROM (select non_negative_difference(\"result\") AS balance_increase FROM \"flexpool_miner_balance\" WHERE \"miner\" =~ /^$miner$/ AND $timeFilter) GROUP BY time(1d) TZ('$timezone');",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "blocks" }
   ],
   "targets": [
    {
     "alias": "blocks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(blocks_increase) FROM (select non_negative_difference(\"confirmed\") AS blocks_increase FROM \"flexpool_pool_block_count\" WHERE $timeFilter) GROUP BY time(1d) TZ('$timezone');",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly revenue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ETH", "label": "income" }
   ],
   "targets": [
    {
     "alias": "income",
     "groupBy": [
      { "params": [ "31d" ], "type": "time" }
     ],
     "measurement": "flexpool_miner_balance",
     "query": "SELECT sum(balance_increase)/1000000000000000000 FROM (select non_negative_difference(\"result\") AS balance_increase FROM \"flexpool_miner_balance\" WHERE \"miner\" =~ /^$miner$/ AND $timeFilter) GROUP BY time(31d) TZ('$timezone');",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "31d" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000000000000000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "income (fiat)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(balance_increase)/1000000000000000000*$exchange_rate FROM (select non_negative_difference(\"result\") AS balance_increase FROM \"flexpool_miner_balance\" WHERE \"miner\" =~ /^$miner$/ AND $timeFilter) GROUP BY time(31d) TZ('$timezone');",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "blocks" }
   ],
   "targets": [
    {
     "alias": "blocks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(blocks_increase) FROM (select non_negative_difference(\"confirmed\") AS blocks_increase FROM \"flexpool_pool_block_count\" WHERE $timeFilter) GROUP BY time(31d) TZ('$timezone');",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unpaid balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ETH", "label": "balance" }
   ],
   "targets": [
    {
     "alias": "balance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_balance",
     "query": "SELECT mean(\"result\")/1000000000000000000 FROM \"flexpool_miner_balance\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "balance (fiat)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"result\")/1000000000000000000*$exchange_rate FROM \"flexpool_miner_balance\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unpaid balance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "balance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_balance",
     "query": "SELECT mean(\"result\")/1000000000000000000 FROM \"flexpool_miner_balance\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "balance (fiat)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"result\")/1000000000000000000*$exchange_rate  FROM \"flexpool_miner_balance\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Estimated daily revenue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ETH" }
   ],
   "targets": [
    {
     "alias": "revenue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_daily_revenue_estimation",
     "query": "SELECT mean(\"result\")/1000000000000000000 FROM \"flexpool_miner_daily_revenue_estimation\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    }
   ]
  },
  {
   "title": "Estimated daily revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "revenue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_daily_revenue_estimation",
     "query": "SELECT mean(\"result\")/1000000000000000000 FROM \"flexpool_miner_daily_revenue_estimation\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "revenue (fiat)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"result\")/1000000000000000000*$exchange_rate FROM \"flexpool_miner_daily_revenue_estimation\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Paid by the pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ETH", "label": "paid" }
   ],
   "targets": [
    {
     "alias": "paid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_paid",
     "query": "SELECT mean(\"result\")/1000000000000000000 FROM \"flexpool_miner_paid\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "paid (fiat)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"result\")/1000000000000000000*$exchange_rate FROM \"flexpool_miner_paid\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Paid by the pool",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "paid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_paid",
     "query": "SELECT mean(\"result\")/1000000000000000000 FROM \"flexpool_miner_paid\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "result" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "paid (fiat)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"result\")/1000000000000000000*$exchange_rate FROM \"flexpool_miner_paid\" WHERE (\"miner\" =~ /^$miner$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last payments",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "measurement": "flexpool_miner_payments",
     "query": "SELECT \"amount\"/1000000000000000000,  \"amount\"/1000000000000000000*$exchange_rate as \"amount (fiat)\",  \"duration\" FROM \"flexpool_miner_payments\" WHERE (\"miner\" =~ /^$miner$/) order by time desc limit 6",
     "select": [
      [
       { "params": [ "amount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    }
   ]
  },
  { "title": "Hashrates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Hashrates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "alias": "effective",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "current_effective_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "reported",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "current_reported_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "daily effective",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "daily_effective_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    }
   ]
  },
  {
   "title": "Current effective hashrate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "effective",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "current_effective_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "reported",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "current_reported_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "daily effective",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "daily_effective_hashrate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    }
   ]
  },
  { "title": "Shares", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Daily shares",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "valid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "daily_valid_shares" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "stale",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "daily_stale_shares" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    },
    {
     "alias": "invalid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "daily_invalid_shares" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Valid shares",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "valid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "daily_valid_shares" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    }
   ]
  },
  {
   "title": "Stale shares",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "stale",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "daily_stale_shares" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    }
   ]
  },
  {
   "title": "Invalid shares",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "invalid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flexpool_miner_stats",
     "select": [
      [
       { "params": [ "daily_invalid_shares" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "miner", "operator": "=~", "value": "/^$miner$/" }
     ]
    }
   ]
  }
 ]
}